metaprot/data/urls.py
from django.conf.urls import url
from django.core.urlresolvers import reverse, reverse_lazy
from .views import (
            DocumentListView, DTAListView, SQTListView, MS1ListView, MS2ListView, 
            DTADetailView, SQTDetailView, MS1DetailView, MS2DetailView,
            DTAParseView, DTAJSONView,
            DocumentCreateView, 
            DocumentDeleteView,
)

urlpatterns = [
                url(r'^$', DocumentCreateView.as_view(), name='index'),
                url(r'^(?P<pk>\d+)/delete$', DocumentDeleteView.as_view(), name='delete'),
#                url(r'^delete/(?P<pk>\d+)/$', DocumentDeleteView.as_view(), name='delete'),
                url(r'^dta/$', DTAListView.as_view(), name='DTA'),
                url(r'^sqt/$', SQTListView.as_view(), name='SQT'),
                url(r'^ms1/$', MS1ListView.as_view(), name='MS1'),
                url(r'^ms2/$', MS2ListView.as_view(), name='MS2'),
                url(r'^dta/(?P<pk>\d+)/$', DTADetailView.as_view(), name='DTA-detail'),
                url(r'^sqt/(?P<pk>\d+)/$', SQTDetailView.as_view(), name='SQT-detail'),
                url(r'^ms1/(?P<pk>\d+)/$', MS1DetailView.as_view(), name='MS1-detail'),
                url(r'^ms2/(?P<pk>\d+)/$', MS2DetailView.as_view(), name='MS2-detail'),
                url(r'^dta/(?P<pk>\d+)/json/$', DTAJSONView.as_view(), name='DTA-json'),
                url(r'^dta/(?P<pk>\d+)/parse/$', DTAParseView.as_view(), name='DTA-parse'),
]

metaprot/metaprot/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.contrib import admin
from django.views.static import serve
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name="index.html"), name='index'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^dbstats/', include('dbstats.urls', namespace='dbstats')),
    url(r'^data/', include('data.urls', namespace='data')),
    url(r'^analysis/', include('analysis.urls', namespace='analysis')),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^files/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
   ]

metaprot/data/models.py
import os
from base64 import b16encode
from django.db import models

def _create_hash():
    """ returns a random hash of length 20 """
    return b16encode(os.urandom(10)).decode('utf-8')

def _content_file_name(instance, filename):
    name = _create_hash() + os.path.splitext(filename)[1]
    return '/'.join(['data', name])

class Document(models.Model):

    """Model for a generic uploaded proteomics file (MS1, MS2, SQT, DTASelect-filter.txt)
    """

    FILE_TYPE_CHOICES = (
        ('DTA', 'DTA'),
        ('SQT', 'SQT'),
        ('MS1', 'MS1'),
        ('MS2', 'MS2'),
    )

    docfile = models.FileField(upload_to=_content_file_name)
    #private_hash = models.CharField(max_length=20, null=True, default=_create_hash, unique=True)
    file_type = models.CharField(max_length=3, null=True, choices=FILE_TYPE_CHOICES)
    description = models.TextField(max_length=500, blank=True)
    last_modified = models.DateTimeField(auto_now=True, null=True)
    #created = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    slug = models.SlugField(max_length=200, blank=True)

#    class Meta:
#        managed = False

    def __str__(self):
        return self.docfile.name

    def save(self, *args, **kwargs):
        self.slug = self.docfile.name
        super(Document, self).save(*args, **kwargs)

class DTAFile(models.Model):
    document_id = models.OneToOneField(Document, unique=True, primary_key=True)
    parsed = models.BooleanField(default=False)
    parsed_json = models.FileField(upload_to='documents/%Y/%m/%d', null=True)
    last_processed = models.DateTimeField(auto_now=True, null=True)

metaprot/data/forms.py
# -*- coding: utf-8 -*-
from django import forms
from .models import Document

class DocumentForm(forms.ModelForm):

    """Represents an uploaded document file
        (DTASelect-filter.txt, SQT, MS1, MS2)
    """

    class Meta:
        model = Document
        fields = ['docfile', 'file_type', 'description', 'slug']

metaprot/data/views.py
#from django.shortcuts import render

from django.shortcuts import render_to_response
from django.template import RequestContext
from django.http import HttpResponseRedirect, HttpResponse, HttpResponseNotFound
from django.core.urlresolvers import reverse, reverse_lazy
from django.contrib import messages

from django.views.generic import TemplateView, ListView, CreateView, DeleteView, DetailView

from rest_framework.renderers import JSONRenderer
from rest_framework.response import Response as RestResponse # to prevent potential name conflicts
from rest_framework.views import APIView
from rest_framework import status as rest_status # to prevent potential name conflicts

from .views_listviews import *
from .forms import DocumentForm
from .models import Document, DTAFile

import os
import datetime

class DocumentCreateView(CreateView):
    model = Document
    form_class = DocumentForm
    success_url = reverse_lazy('index')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.handle_uploaded_file(self.request.FILES['docfile'])
        self.object.save()
        return HttpResponseRedirect(reverse_lazy('data:index'))

    def handle_uploaded_file(self, f): ## can probably remove this.
        with open('_file_upload', 'wb') as destination:
            for chunk in f.chunks():
                destination.write(chunk)

    def form_invalid(self, form):
        return HttpResponse(content=form, status=400, content_type='application/json')

    def get_context_data(self, **kwargs):
        """build queryset for CreateView...
        """
        
        kwargs['object_list'] = Document.objects.all().order_by('-last_modified')[:5]
        return super(DocumentCreateView, self).get_context_data(**kwargs)

class DocumentDeleteView(DeleteView):
    model = Document
    success_url = reverse_lazy('data:index')
    # should also delete associated files from DTAFile, MS2File, etc. if available (parsed JSON, for example)

class DocumentDetailView(DetailView):
    model = Document

    def get_context_data(self, **kwargs):
        context = super(DocumentDetailView, self).get_context_data(**kwargs)

        properties_list = []
        properties_list.append(('File type', context['object'].file_type))
        properties_list.append(('Details', context['object'].description))
        properties_list.append(('File size (MB)', self.convert_file_size(context['object'].docfile.size)))
        properties_list.append(('File location', context['object'].docfile.url))
        properties_list.append(('File uploaded', context['object'].last_modified))
        context['properties'] = properties_list

        return context

    def convert_file_size(self, file_size_bytes):
        """Converts input size in bytes to megabytes (string)"""
        return '{0:.3f}'.format(file_size_bytes/(1024**2))+' MB'


class DTADetailView(DocumentDetailView):

    """DetailView for DTASelect-filter.txt files
    """

    template_name_suffix = '_dta_detail'

    def get_context_data(self, **kwargs):
        context = super(DTADetailView, self).get_context_data(**kwargs)

        try:
            dta_record = DTAFile.objects.get(pk=self.kwargs['pk'])
        except DTAFile.DoesNotExist:
            # if no DTAFile instance exists for this file
            # and the file is a DTA file, create a new DTAFile instance
            if context['object'].file_type == 'DTA':
                dta_record = DTAFile(pk=self.kwargs['pk']) ## add other init params if desired
                dta_record.save()
            else:
                # not a DTA file... should return something more useful/verbose than this...
                context['properties'] = [('ERROR', 'file_type not "DTA"')]
                return context

        context['properties'].append(('Parsed?', dta_record.parsed))
        if dta_record.parsed:
            context['parsed'] = True
            context['properties'].append(('Parsed file path', dta_record.parsed_json.url))
            context['properties'].append(('JSON output', self.request.path+'json'))
        context['properties'].append(('Last processed', dta_record.last_processed))

        return context

class DTAParseView(DocumentDetailView):
    
    """View that parses DTASelect file (if necessary)
    """

    model = Document
    #template_name = 'analysis/document_dta_detail.html'
    template_name = 'data/dta_parse_success.html'

    def get_context_data(self, **kwargs):
        context = super(DocumentDetailView, self).get_context_data(**kwargs)

        if context['object'].file_type != 'DTA':
            # not a DTA file? return immediately...
            return context
        else:
            import io
            import json
            from .parsers import dta
            from django.core.files import File
            try:
                dta_record = DTAFile.objects.get(pk=self.kwargs['pk'])
            except DTAFile.DoesNotExist:
                # shouldn't get here...
                raise
                return context

            file_name = context['object'].docfile.name
            file_path_full = str(context['object'].docfile.file)
            parsed_dta_dict = list(dta.dta_select_parser(file_path_full))

            f = io.StringIO()
            f.write(json.dumps(parsed_dta_dict))
            django_file = File(f)
            dta_record.parsed_json.save(file_name+'.json', django_file)
            dta_record.parsed = True
            dta_record.save()
            f.close()
            context['dtafile_parsed_file'] = dta_record.parsed_json.url
            print(context.keys())

            return context

class DTAJSONView(APIView):
    
    """View that returns a JSON response using parsed
        DTASelect-filter.txt (DTAFile) output
    """

    renderer_classes = (JSONRenderer, )

    def get(self, request, pk, format=None):
        
        try:
            dta_record = DTAFile.objects.get(pk=pk)
        except DTAFile.DoesNotExist:
            return RestResponse({'file':'not found'}, status=rest_status.HTTP_404_NOT_FOUND)

        if not dta_record.parsed:
            return RestResponse({'file':'not yet parsed'}, status=rest_status.HTTP_412_PRECONDITION_FAILED)

        import json
        json_file_path = str(dta_record.parsed_json.file)
        with open(json_file_path) as f:
            content = json.load(f)

        return RestResponse(content)

class SQTDetailView(DocumentDetailView):

    """DetailView for SQT files
    """

    template_name_suffix = '_sqt_detail'

    def get_context_data(self, **kwargs):
        context = super(SQTDetailView, self).get_context_data(**kwargs)

        context['properties'].append(('# scans', self.get_number_scans(context['object'].docfile.url)))

        return context

    def get_number_scans(self, file_path):
        # some code to count # scans
        return 0

class MS1DetailView(DocumentDetailView):

    """DetailView for MS1 files
    """

    template_name_suffix = '_ms1_detail'

class MS2DetailView(DocumentDetailView):

    """DetailView for MS2 files
    """

    template_name_suffix = '_ms2_detail'

metaprot/data/templates/data/document_base.html
{% extends "base.html" %}

{% block title %} - Analysis{% endblock %}

{% block content %}
<h1>View and Manage Data{% block title_additions %}{% endblock %}</h1>
<p class="lead">Choose from recently uploaded files {% block subtitle_additions %}{% endblock %}</p>

{% if messages %}
    {% for message in messages %}
        <div class="alert alert-info" role="alert">{{ message }}</div>
    {% endfor %}
{% endif %}

<div class="row display-table">
    <div class="col-md-7 display-cell">
        <h3>Recent data files</h3>
    </div>
    <div class="col-md-1 display-cell">
        <a href="{% url 'data:index' %}" class="btn btn-default{% block all_active %}{% endblock %}" role="button">All files</a>
    </div>
    <div class="col-md-1 display-cell">
        <a href="{% url 'data:MS1' %}" class="btn btn-warning{% block ms1_active %}{% endblock %}" role="button">MS1 files</a>
    </div>
    <div class="col-md-1 display-cell">
        <a href="{% url 'data:MS2' %}" class="btn btn-warning{% block ms2_active %}{% endblock %}" role="button">MS2 files</a>
    </div>
    <div class="col-md-1 display-cell">
        <a href="{% url 'data:SQT' %}" class="btn btn-warning{% block sqt_active %}{% endblock %}" role="button">SQT files</a>
    </div>
    <div class="col-md-1 display-cell">
        <a href="{% url 'data:DTA' %}" class="btn btn-warning{% block dta_active %}{% endblock %}" role="button">DTASelect files</a>
    </div>
</div>

<table class="table table-striped">
    <thead>
        <tr>
            <th class="text-center">File Name</th> <!-- slug -->
            <th class="text-center">File Type</th> <!-- file_type -->
            <th class="text-center">Description</th> <!-- description -->
            <th class="text-center">Last Modified</th> <!-- last_modified -->
            <th class="text-center"></th> <!-- view button -->
            <th class="text-center"></th> <!-- edit button -->
            <th class="text-center"></th> <!-- delete button -->
        </tr>
    </thead>
    {% if object_list %}
    {% for document in object_list %}
    <tr>
        <td class="text-center">
            <a href="{{ document.docfile.url }}">{{ document.slug }}</a>
        </td>
        <td class="text-center">{{ document.file_type }}</td>
        <td class="text-center">{{ document.description }}</td>
        <td class="text-center">{{ document.last_modified|timesince}}</td>
        <td class="text-center">
            <a href="{% if document.file_type == 'DTA' %}
                        {% url 'data:DTA-detail' document.id %}
                    {% elif document.file_type == 'SQT' %}
                        {% url 'data:SQT-detail' document.id %}
                    {% elif document.file_type == 'MS1' %}
                        {% url 'data:MS1-detail' document.id %}
                    {% elif document.file_type == 'MS2' %}
                        {% url 'data:MS2-detail' document.id %}
                    {% endif %}"><button type="button" class="btn btn-success btn-sm">View</button></a>
        </td>
        <td class="text-center">
            <a href=""><button type="button" class="btn btn-primary btn-sm">Edit</button></a>
        </td>
        <td class="text-center">
            <a href="{% url 'data:delete' document.id %}"><button type="button" class="btn btn-danger btn-sm">Delete</button></a>
        </td>
    {% endfor %}
    {% else %}
    <tr>
        <td class="text-center danger">No documents to display</td>
    </tr>
    {% endif %}
</table>

<br>

{% block upload_block %}
{% endblock %}

{% endblock %}

metaprot/data/templates/data/document_confirm_delete.html
{% extends "base.html" %}

{% block title %} - Confirm File Deletion {% endblock %}

{% block content %}
<h1>Delete file?</h1>

{% if messages %}
    {% for message in messages %}
        <div class="alert alert-info" role="alert">{{ message }}</div>
    {% endfor %}
{% endif %}

<!-- Confirm Document Delete -->
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <p>Are you sure you want to permanently delete file "{{ object }}"?</p>
    <p><input type="submit" value="Confirm" class="btn btn-danger" /></p>
</form>
        
{% endblock %}

metaprot/data/templates/data/document_detail_base.html
{% extends "base.html" %}

{% block content %}

<h1>File Information</h1>
<h2><small>{{ object.slug }}</small></h2>

<h3>Properties</h3>

<table class="table table-striped">
    {% for prop in properties %}
    <tr>
        <td>
            <strong>{{ prop.0 }}</strong>
        </td>
        <td>
            {{ prop.1 }}
        </td>
    </tr>
    {% endfor %}
</table>

{% block available_analyses %}
{% endblock %}

{% endblock %}

metaprot/data/templates/data/document_dta_detail.html
{% extends "data/document_detail_base.html" %}

{% block title %} - DTASelect-filter File Detail {% endblock %}

{% block content %}
{{ block.super}}

{% if not parsed %}
<a href="{% url 'data:DTA-parse' document.id %}" class="btn btn-danger">Parse file</a>
{% endif %}

{% endblock %}

metaprot/data/templates/data/document_dta_list.html
{% extends "data/document_base.html" %}

{% block title_additions %}<small> -- DTASelect-filter files</small>{% endblock %}

{% block dta_active %} active{% endblock %}

metaprot/data/templates/data/document_form.html
{% extends "data/document_base.html" %}

{% block all_active %} active{% endblock %}

{% block subtitle_additions %}or upload a new file below{% endblock %}

{% block upload_block %}
<h3>Upload new file</h3>
    <div class="row">
        <div class="col-md-6">
        <!-- Upload form. Note enctype attribute! -->
        <form action="{% url "data:index" %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
        {{ form.non_field_errors }}
<!--            <p>
                {{ form.docfile.label_tag }}
            </p>-->
            <p>
                {{ form.docfile.help_text }}
            </p>
            <p>
                {{ form.docfile.errors }}
            </p>
            <div class="form-group">
                <label for="id_docfile">File input</label>
                <span class="form-control">{{ form.docfile }}</span>
                <p class="help-block">Allowed file types: MS1, MS2, SQT, DTASelect-filter.txt</p>
            </div>
            <div class="form-group">
                <label for="{{ form.file_type.auto_id }}">File type</label>
                <span class="form-control">{{ form.file_type }}</span>
            </div>
            {{ form.last_modified }} <!-- hidden -->
            <div class="form-group">
                <label for="{{ form.description.auto_id }}">Description</label>
                <textarea class="form-control" rows="3" placeholder="Enter a concise description of the file" \
                    id="{{ form.description.auto_id }}" name="{{ form.description.html_name }}" maxlength="500"></textarea>
            </div>
            </p>
            <p><input type="submit" value="Upload" class="btn btn-warning btn-lg" /></p>
        </form>
        </div>
    </div>

{% endblock %}

metaprot/data/templates/data/document_ms1_detail.html
{% extends "data/document_detail_base.html" %}

{% block title %} - MS1 File Detail {% endblock %}

metaprot/data/templates/data/document_ms1_list.html
{% extends "data/document_base.html" %}

{% block title_additions %}<small> -- MS1 files</small>{% endblock %}

{% block ms1_active %} active{% endblock %}

metaprot/data/templates/data/document_ms2_detail.html
{% extends "data/document_detail_base.html" %}

{% block title %} - MS2 File Detail {% endblock %}

metaprot/data/templates/data/document_ms2_list.html
{% extends "data/document_base.html" %}

{% block title_additions %}<small> -- MS2 files</small>{% endblock %}

{% block ms2_active %} active{% endblock %}

metaprot/data/templates/data/document_sqt_detail.html
{% extends "data/document_detail_base.html" %}

{% block title %} - SQT File Detail {% endblock %}

metaprot/data/templates/data/document_sqt_list.html
{% extends "data/document_base.html" %}

{% block title_additions %}<small> -- SQT files</small>{% endblock %}

{% block sqt_active %} active{% endblock %}

metaprot/data/templates/data/dta_parse_success.html
{% extends 'base.html' %}

{% block content %}

<h3>Parsed file <strong>{{ document.docfile.url }}</strong> (Document ID {{ document.id }})</h3>

<p>
    <h3><small>Parsed file JSON output saved to {{ dtafile_parsed_file }} </small></h3>
</p>

<a href="{% url 'data:DTA-detail' document.id %}" class="btn btn-success">Go back</a>

{% endblock %}