metaprot/data/urls.py
from django.conf.urls import url
from django.core.urlresolvers import reverse, reverse_lazy
from .views import (
            DocumentListView, DTAListView, SQTListView, MS1ListView, MS2ListView, 
            DTADetailView, SQTDetailView, MS1DetailView, MS2DetailView,
            DTAParseView, DTAJSONView,
            DocumentCreateView, 
            DocumentDeleteView,
)

urlpatterns = [
                url(r'^$', DocumentCreateView.as_view(), name='index'),
                url(r'^(?P<pk>\d+)/delete$', DocumentDeleteView.as_view(), name='delete'),
#                url(r'^delete/(?P<pk>\d+)/$', DocumentDeleteView.as_view(), name='delete'),
                url(r'^dta/$', DTAListView.as_view(), name='DTA'),
                url(r'^sqt/$', SQTListView.as_view(), name='SQT'),
                url(r'^ms1/$', MS1ListView.as_view(), name='MS1'),
                url(r'^ms2/$', MS2ListView.as_view(), name='MS2'),
                url(r'^dta/(?P<pk>\d+)/$', DTADetailView.as_view(), name='DTA-detail'),
                url(r'^sqt/(?P<pk>\d+)/$', SQTDetailView.as_view(), name='SQT-detail'),
                url(r'^ms1/(?P<pk>\d+)/$', MS1DetailView.as_view(), name='MS1-detail'),
                url(r'^ms2/(?P<pk>\d+)/$', MS2DetailView.as_view(), name='MS2-detail'),
                url(r'^dta/(?P<pk>\d+)/json/$', DTAJSONView.as_view(), name='DTA-json'),
                url(r'^dta/(?P<pk>\d+)/parse/$', DTAParseView.as_view(), name='DTA-parse'),
]

metaprot/dbstats/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.status, name='status'),
    # url(r'^$', views.index, name='index'),
]

metaprot/metaprot/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.contrib import admin
from django.views.static import serve
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name="index.html"), name='index'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^dbstats/', include('dbstats.urls', namespace='dbstats')),
    url(r'^data/', include('data.urls', namespace='data')),
    url(r'^analysis/', include('analysis.urls', namespace='analysis')),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^files/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
   ]

metaprot/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>Metaprot{% block title %}{% endblock %}</title>

        <!-- Bootstrap -->
        {% load staticfiles %}
        <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/styles.css' %}" rel="stylesheet">
        <!--
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
        <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
        -->
        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
        {% block head_additions %}
        {% endblock %}
    </head>

    <body>
        {% block navbar %}

        <nav class="navbar navbar-default">
          <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#">Metaprot</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                <li class="active"><a href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a></li>
                <li><a href="#">Search ComPIL</a></li>
                <li><a href="#">Build ComPIL</a></li>
                <li><a href="{% url 'data:index' %}">View Data</a></li>
                <li><a href="{% url 'analysis:index' %}">Analyze Data</a></li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Tools <span class="caret"></span></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="{% url 'dbstats:status' %}">Database status</a></li>
                    <li><a href="#">Another action</a></li>
                    <li class="divider"></li>
                    <li><a href="">Upload a file</a></li>
                    <li class="divider"></li>
                    <li><a href="#">One more separated link</a></li>
                  </ul>
                </li>
              </ul>
              <ul class="nav navbar-nav navbar-right">
                <!-- <li><a href="#">Link</a></li> -->
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Links <span class="caret"></span></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="http://www.scripps.edu/wolan">Wolan Lab</a></li>
                    <li><a href="http://wolands.scripps.edu/">WolanDS</a></li>
                    <li class="divider"></li>
                    <li><a href="http://sulab.org/">Su Lab</a></li>
                  </ul>
                </li>
              </ul>
            </div><!-- /.navbar-collapse -->
          </div><!-- /.container-fluid -->
        </nav>

        {% endblock %}
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>

        <div class="container">
        {% block content %}
        {% endblock %}
        </div>
    </body>
</html>

metaprot/templates/index.html
{% extends "base.html" %}

{% block title %} - Main Page{% endblock %}

{% block content %}
<h1>Metaprot</h1>
<p class="lead">a collection of tools for metaproteomic data analysis</p>

<div class="row">
  <div class="col-md-3 text-center">
    <a href="search" class="btn btn-default btn-lg">
      &nbsp;<span class="glyphicon glyphicon-search" aria-hidden="true" style="vertical-align:-1px"></span>&nbsp;&nbsp;&nbsp;Search ComPIL&nbsp;
    </a>
  </div>
  <div class="col-md-3 text-center">
    <a href="build" class="btn btn-default btn-lg">
      &nbsp;<span class="glyphicon glyphicon-cloud-upload" aria-hidden="true" style="vertical-align:-1px"></span>&nbsp;&nbsp;&nbsp;Build ComPIL&nbsp;
    </a>
  </div>
  <div class="col-md-3 text-center">
    <a href="{% url 'data:index' %}" class="btn btn-default btn-lg">
      &nbsp;<span class="glyphicon glyphicon-th-list" aria-hidden="true" style="vertical-align:-1px"></span>&nbsp;&nbsp;&nbsp;View Data&nbsp;
    </a>
  </div>
  <div class="col-md-3 text-center">
    <a href="{% url 'analysis:index' %}" class="btn btn-default btn-lg">
      &nbsp;<span class="glyphicon glyphicon-equalizer" aria-hidden="true" style="vertical-align:-1px"></span>&nbsp;&nbsp;&nbsp;Analyze Data&nbsp;
    </a>
  </div>
</div>
{% endblock %}