metaprot/analysis/urls.py
from django.conf.urls import url
from django.core.urlresolvers import reverse, reverse_lazy
from .views import (
                PlotListView,
)

urlpatterns = [
                url(r'^$', PlotListView.as_view(), name='index'),
#                url(r'^delete/(?P<pk>\d+)/$', DocumentDeleteView.as_view(), name='delete'),
#                url(r'^dta/$', DTAListView.as_view(), name='DTA'),
#                url(r'^sqt/$', SQTListView.as_view(), name='SQT'),
#                url(r'^ms1/$', MS1ListView.as_view(), name='MS1'),
#                url(r'^ms2/$', MS2ListView.as_view(), name='MS2'),
#                url(r'^dta/(?P<pk>\d+)/$', DTADetailView.as_view(), name='DTA-detail'),
#                url(r'^sqt/(?P<pk>\d+)/$', SQTDetailView.as_view(), name='SQT-detail'),
#                url(r'^ms1/(?P<pk>\d+)/$', MS1DetailView.as_view(), name='MS1-detail'),
#                url(r'^ms2/(?P<pk>\d+)/$', MS2DetailView.as_view(), name='MS2-detail'),
#                url(r'^dta/(?P<pk>\d+)/json/$', DTAJSONView.as_view(), name='DTA-json'),
#                url(r'^dta/(?P<pk>\d+)/parse/$', DTAParseView.as_view(), name='DTA-parse'),
]

metaprot/data/urls.py
from django.conf.urls import url
from django.core.urlresolvers import reverse, reverse_lazy
from .views import (
            DocumentListView, DTAListView, SQTListView, MS1ListView, MS2ListView, 
            DTADetailView, SQTDetailView, MS1DetailView, MS2DetailView,
            DTAParseView, DTAJSONView,
            DocumentCreateView, 
            DocumentDeleteView,
)

urlpatterns = [
                url(r'^$', DocumentCreateView.as_view(), name='index'),
                url(r'^(?P<pk>\d+)/delete$', DocumentDeleteView.as_view(), name='delete'),
#                url(r'^delete/(?P<pk>\d+)/$', DocumentDeleteView.as_view(), name='delete'),
                url(r'^dta/$', DTAListView.as_view(), name='DTA'),
                url(r'^sqt/$', SQTListView.as_view(), name='SQT'),
                url(r'^ms1/$', MS1ListView.as_view(), name='MS1'),
                url(r'^ms2/$', MS2ListView.as_view(), name='MS2'),
                url(r'^dta/(?P<pk>\d+)/$', DTADetailView.as_view(), name='DTA-detail'),
                url(r'^sqt/(?P<pk>\d+)/$', SQTDetailView.as_view(), name='SQT-detail'),
                url(r'^ms1/(?P<pk>\d+)/$', MS1DetailView.as_view(), name='MS1-detail'),
                url(r'^ms2/(?P<pk>\d+)/$', MS2DetailView.as_view(), name='MS2-detail'),
                url(r'^dta/(?P<pk>\d+)/json/$', DTAJSONView.as_view(), name='DTA-json'),
                url(r'^dta/(?P<pk>\d+)/parse/$', DTAParseView.as_view(), name='DTA-parse'),
]

metaprot/metaprot/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.contrib import admin
from django.views.static import serve
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name="index.html"), name='index'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^dbstats/', include('dbstats.urls', namespace='dbstats')),
    url(r'^data/', include('data.urls', namespace='data')),
    url(r'^analysis/', include('analysis.urls', namespace='analysis')),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^files/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
   ]

metaprot/analysis/models.py
from django.db import models

class Plot(models.Model):

    """Table representing available analyses and their params/info"""

    FILE_TYPE_CHOICES = (
        ('DTA', 'DTA'),
        ('SQT', 'SQT'),
        ('MS1', 'MS1'),
        ('MS2', 'MS2'),
    )

    name = models.CharField(max_length=200)
    description = models.TextField(max_length=500)
    supported_file_type = models.CharField(max_length=3, choices=FILE_TYPE_CHOICES)
    last_modified = models.DateTimeField(auto_now=True, null=True)

metaprot/analysis/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, CreateView, DeleteView, DetailView

from .models import Plot

class PlotListView(ListView):
    
    model = Plot

    def get_context_data(self, **kwargs):
        context = super(PlotListView, self).get_context_data(**kwargs)
        # context additions here
        return context

metaprot/analysis/templates/analysis/plot_list.html
{% extends "base.html" %}

{% block title %} - Analysis{% endblock %}

{% block head_additions %}
<link
    href="http://cdn.pydata.org/bokeh/release/bokeh-0.9.1.min.css"
    rel="stylesheet" type="text/css">
{% endblock %}

{% block content %}

<h1>Analyze Data{% block title_additions %}{% endblock %}</h1>
<p class="lead">Choose from available analyses{% block subtitle_additions %}{% endblock %}</p>

{% if messages %}
    {% for message in messages %}
        <div class="alert alert-info" role="alert">{{ message }}</div>
    {% endfor %}
{% endif %}

<div class="row display-table">
    <div class="col-md-7 display-cell">
        <h3>Recent data files</h3>
    </div>
    <div class="col-md-1 display-cell">
        <a href="{% url 'data:index' %}" class="btn btn-default{% block all_active %}{% endblock %}" role="button">All files</a>
    </div>
    <div class="col-md-1 display-cell">
        <a href="{% url 'data:MS1' %}" class="btn btn-warning{% block ms1_active %}{% endblock %}" role="button">MS1 files</a>
    </div>
    <div class="col-md-1 display-cell">
        <a href="{% url 'data:MS2' %}" class="btn btn-warning{% block ms2_active %}{% endblock %}" role="button">MS2 files</a>
    </div>
    <div class="col-md-1 display-cell">
        <a href="{% url 'data:SQT' %}" class="btn btn-warning{% block sqt_active %}{% endblock %}" role="button">SQT files</a>
    </div>
    <div class="col-md-1 display-cell">
        <a href="{% url 'data:DTA' %}" class="btn btn-warning{% block dta_active %}{% endblock %}" role="button">DTASelect files</a>
    </div>
</div>

<table class="table table-striped">
    <thead>
        <tr>
            <th class="text-center">Analysis Name</th> <!-- name -->
            <th class="text-center">Description</th> <!-- description -->
            <th class="text-center">File Type Supported</th> <!-- file_type -->
            <th class="text-center">Last Modified</th> <!-- last_modified -->
        </tr>
    </thead>
    {% if object_list %}
    {% for plot_obj in object_list %}
    <tr>
        <td class="text-center">
            {{ plot_obj.name }}
        </td>
        <td class="text-center">
            {{ plot_obj.description }}
        </td>
        <td class="text-center">
            {{ plot_obj.supported_file_type }}
        </td>
        <td class="text-center">
            {{ plot_obj.last_modified }}
        </td>
    </tr>
    {% endfor %}
    {% endif %}
</table>

{% block embed_bokeh_js %}<script src="http://cdn.pydata.org/bokeh/release/bokeh-0.9.1.min.js">{% endblock %}

{% endblock %}